name: PostgreSQL Workflow

on: [push]

jobs:
  postgres-job:
    runs-on: ubuntu-22.04

    env:
      DATABASE_NAME: testdb
      SQL_SCRIPT_PATH: ./12_tables.sql

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done

    - name: Create database
      run: |
        psql -h localhost -p 5432 -U postgres -c "CREATE DATABASE $DATABASE_NAME;"

    - name: Run SQL script
      run: |
        psql -h localhost -p 5432 -U postgres -d $DATABASE_NAME -f $SQL_SCRIPT_PATH

    - name: List tables
      run: |
        psql -h localhost -p 5432 -U postgres -d $DATABASE_NAME -c "\dt"
