name: DbSchema Workflow

on: [push]

jobs:
  dbschema-job:
    runs-on: ubuntu-22.04

    env:
      PG_USER: postgres
      PG_PWD: postgres
      DATABASE_NAME: testdb
      SQL_SCRIPT_PATH: ./12_tables.sql
      GROOVY_SCRIPT: example_script.groovy

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PWD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PostgreSQL client
      run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client

    - name: Turn on PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        
    - name: Create database
      run: |
        PGPASSWORD=${{ env.PG_USER }} psql -U postgres -tc "SELECT 'CREATE DATABASE ${{ env.DATABASE_NAME }};'"

    - name: Run SQL script
      run: |
        PGPASSWORD=$POSTGRES_PASSWORD psql -h localhost -p 5432 -U postgres -d $DATABASE_NAME -f $SQL_SCRIPT_PATH

    - name: Install Make
      run: sudo apt-get install -y make

    - name: Run Makefile
      run: make

    - name: Build Docker image for DbSchema
      run: |
        docker build -t dbschema-image:latest .

    - name: Run DbSchema in headless mode
      run: |
        docker run --rm -v $(pwd):/workspace dbschema-image:latest \
          java -Djava.awt.headless=true \
               -Dglass.platform=Monocle \
               -Dmonocle.platform=Headless \
               -Dprism.order=sw \
               -Dprism.verbose=true \
               -Djavafx.platform=monocle \
               --module-path /opt/javafx-sdk-17.0.2/lib \
               --add-modules javafx.controls,javafx.base,javafx.graphics,javafx.swing \
               --add-exports javafx.graphics/com.sun.glass.ui=ALL-UNNAMED \
               --add-exports javafx.graphics/com.sun.javafx.util=ALL-UNNAMED \
               --add-exports javafx.graphics/com.sun.javafx.logging=ALL-UNNAMED \
               --add-exports javafx.base/com.sun.javafx.logging=ALL-UNNAMED \
               -cp /workspace/app/lib/*:/opt/javafx-sdk-17.0.2/lib/openjfx-monocle-17.0.10.jar \
               com.wisecoders.dbs.DbSchema -x /workspace/$GROOVY_SCRIPT
