name: DbSchema Workflow

on: [push]

jobs:
  dbschema-job:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Make
      run: sudo apt-get install -y make

    - name: Run Makefile
      run: make

    - name: Build and Run Docker Compose
      run: |
        # Run Docker Compose in detached mode
        sudo docker compose up --build -d --wait --wait-timeout 30

    - name: Wait for app to exit
      run: ./wait-for-app.sh

    - name: Copy Artifacts
      run: |
        # Ensure the output directory exists
        mkdir -p output
        # Copy generated HTML files from the Docker container to the host
        sudo docker cp $(sudo docker ps -q --filter "name=app"):home/dbschema/output/. ./output

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dbschema-html-output
        path: output/*
